ECCV code version.
unibas-gravis/icp-proposal pull request #1
Opened 2020-08-23 18:25 UTC by madsendennis

BFM experiments updated to use an analytically defined GPMM instead of the learned BFM.

2020-08-24 13:48 UTC, Andreas-Forster requested changes
I am most unhappy with too much commented-out code, where it is not clear why it should remain in there. If there is no reason, then delete it.

Further, I proposed a change to a loop. However, this will slightly change the function it will evaluate. I think the proposed code is better/more precise. The old version has some slack for a decision which I think is not a good thing.

2020-08-24 13:48 UTC, Andreas-Forster commented on src/main/scala/api/other/RegistrationComparison.scala
> +  private def avgDistanceBoundaryAware(m1: TriangleMesh[_3D], m2: TriangleMesh[_3D]): (Double, Double) = {
I do not like m1 and m2 as they have clearer meaning.

2020-08-24 13:48 UTC, Andreas-Forster commented on src/main/scala/api/other/RegistrationComparison.scala
> +      val pTarget = m2.operations.closestPointOnSurface(p).point
the inside of the loop could be replaced with the following one (the for loop could yield an option and then there is not the need to filter, but just a flatten.... ):
```scala
  val instance: TriangleMesh3D = ???
  val target: TriangleMesh3D = ???

  for ( instancePoint <- instance.pointSet.points ) yield {
    val closestTargetPoint: ClosestPointWithType = target.operations.closestPointOnSurface(instancePoint)
    closestTargetPoint match {
      case ClosestPointIsVertex(_, distanceSquared, pid) =>
        if (target.operations.pointIsOnBoundary(pid)) -1.0
        else Math.sqrt(distanceSquared)
      case ClosestPointOnLine(point, distanceSquared, pids, _) =>
        if (target.operations.edgeIsOnBoundary(pids._1,pids._2)) -1.0
        else Math.sqrt(distanceSquared)
      case ClosestPointInTriangle(_, distanceSquared, _, _) =>
        Math.sqrt(distanceSquared)
    }
  }
```

2020-08-24 13:48 UTC, Andreas-Forster commented on src/main/scala/api/sampling/MixedProposalDistributions.scala
> +//      0.5 *: RandomShapeUpdateProposal(model, 1.0, generatedBy = "RandomShape-1.0") +
why not remove commented out code? without a comment explaining why it is still there, this will not help.

2020-08-24 13:48 UTC, Andreas-Forster commented on src/main/scala/api/sampling/MixedProposalDistributions.scala
> +//        0.5 *: RandomShapeUpdateProposal(model, 0.0001, generatedBy = "RandomShape-0.0001") +
same as above

2020-08-24 13:48 UTC, Andreas-Forster commented on src/main/scala/api/sampling/proposals/NonRigidIcpProposal.scala
> +//    val compensatedTo = from.shapeParameters.parameters + (to.shapeParameters.parameters - from.shapeParameters.parameters) / stepLength
remove commented code if no reason is given why it should still be in there

2020-08-24 13:48 UTC, Andreas-Forster commented on src/main/scala/apps/bfm/AlignShapes.scala
> +//      ui.show(meshGroup, alignedMesh, basename)
remove commented code if it is not stated why it should remain in there

2020-08-24 13:48 UTC, Andreas-Forster commented on src/main/scala/apps/femur/IcpProposalRegistration.scala
> +//    val proposalRandom = MixedProposalDistributions.mixedProposalRandom(model)
cleanup commented code in this file, or state why it should be there and when to uncomment the code

2020-08-25 04:30 UTC, marcelluethi reviewed
I added a few minor comments, which you can incorporate if you want. As it is research code, which is mainly used to reproduce the experiments, I am also fine to publish it like this.

2020-08-25 04:30 UTC, marcelluethi commented on src/main/scala/api/other/IcpBasedSurfaceFitting.scala
> +            println(s"Some error occured in IcpBasedSurfaceFITTING!!! Iteration: ${numIterations - nbIterations}) / ${numIterations}")
Exceptions should be printed to stderr and not stdout. 
"An error" instead of "Some error".  
Capitalization of FITTING and !!! seems odd

2020-08-25 04:30 UTC, marcelluethi commented on src/main/scala/api/other/RegistrationComparison.scala
> +      if (m2.operations.pointIsOnBoundary(pTargetId)) -1.0
I would use an Option instead of -1 to show that no value could be produced. This makes intention more clear

2020-08-25 04:30 UTC, marcelluethi commented on src/main/scala/api/sampling/SamplingRegistration.scala
>          val bestTheta = bestSamplelogger.currentBestSample().get
Maybe you should do proper error handling here (get will just throw an exception if things don't work as expected)

2020-08-25 04:30 UTC, marcelluethi commented on src/main/scala/apps/bfm/CreateGPModel.scala
> +      val referenceMesh = model.referenceMesh.operations.decimate(2000) // Speed up - but makes the model more coarse
One possibility to speed up the code, while keeping the same resolution for the visualization, is to decimate in the evaluators instead.

2020-08-25 04:30 UTC, marcelluethi commented on src/main/scala/apps/femur/PosteriorVariabilityToMeshColor.scala
> +    val burnInPhase = 300
Optional improvement. Parameters could be put into a config file instead of having them hardcoded

2020-08-25 04:30 UTC, marcelluethi commented on src/main/scala/apps/femur/RandomSamplesFromModel.scala
> +    val perturbationDistr = new MultivariateNormalDistribution(DenseVector.zeros(rank), DenseMatrix.eye[Double](rank) * variance)
this line can be put in else clause

2020-08-26 20:40 UTC, madsendennis commented
Thanks a lot for the feedback. I'll merge the current version such that it is up to date with the ECCV paper.

2020-08-26 20:40 UTC, merged